version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:11.13.0
    environment:
      <<: *COVERAGE_PARAMETERS
    steps:
      - checkout
      - run:
          name: Create coverage report dir
          command: mkdir -p ${COVERAGE_REPORT_DIR}
      - run:
          name: Set up yarn tests
          command: yarn install
      - run:
          name: Run yarn linter
          command: yarn lint
      - run:
          name: Run yarn build
          command: yarn build
      - run:
          name: Run yarn tests
          command: yarn test
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - lcov.info
  deploy-dev:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - run:
          name: Build docker image
          command: docker build . -t polaris-rules-engine
      - run:
          name: Tag docker image
          command: |
            docker tag polaris-rules-engine ghcr.io/polaris-foundation/polaris-rules-engine:latest
            docker tag polaris-rules-engine ghcr.io/polaris-foundation/polaris-rules-engine:cb-${CIRCLE_BUILD_NUM}
            docker tag polaris-rules-engine ghcr.io/polaris-foundation/polaris-rules-engine:$(git log --pretty=format:'%h' -n 1)
      - run:
          name: Authenticate to GHCR
          command: echo $GHCR_TOKEN | docker login ghcr.io -u jonadaly --password-stdin
      - run:
          name: Push docker image
          command: |
            docker push ghcr.io/polaris-foundation/polaris-rules-engine:latest
            docker push ghcr.io/polaris-foundation/polaris-rules-engine:cb-${CIRCLE_BUILD_NUM}
            docker push ghcr.io/polaris-foundation/polaris-rules-engine:$(git log --pretty=format:'%h' -n 1)
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - deploy-dev:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main